### ISSUE TITLE
Some odd syntax coloring with quoted strings

### ISSUE THREAD

**Issue by bcatubig** [haad/language-Ansible#2]
Hi,

I noticed a couple of syntax color irregularities with the color rendering when using quotes and equal signs. See some examples below.
- `line=""` displays some off colors
  ![1](https://cloud.githubusercontent.com/assets/1383904/10105699/c57eefe8-6375-11e5-888b-5c1e9f7202aa.PNG)
- Similar example
  ![2](https://cloud.githubusercontent.com/assets/1383904/10105731/ef491042-6375-11e5-96c7-2968108a1621.PNG)

Thanks for the great syntax theme!

**Comment by haad** [comment]
I think I have fixed this issue in syntax-coloring-fix branch. Can you try to install package from that branch to your atom ? And let me know if it works for you or not ?

**Comment by haad** [comment]
Branch was merged.
