### ISSUE TITLE
Automatic ansible yml file recognization

### ISSUE THREAD

**Issue by Pseudonomy** [haad/language-Ansible#7]
Please add to docs, took me a while to find out as a new user of atom:

```
"*":
  core:
    customFileTypes:
      "source.ansible": [
        "yml"
      ]
```

Under preferences, config.cson.

**Comment by haad** [comment]
I'm not sure if I understand what would you like me to add. Can you make a pull request ?

**Comment by Pseudonomy** [comment]
Basically just add to readme, so future users know how to apply it on all `.yml` and `.yaml` files. Thanks for your work.

**Comment by haad** [comment]
Fixed in last version
