### ISSUE TITLE
Failed to load snippets error

### ISSUE THREAD

**Issue by lgw4** [haad/language-Ansible#8]
I'm seeing the following error after installing the latest version.

Failed to load snippets from '/Users/lgw4/.atom/packages/language-ansible/snippets/language-ansible.cson'
`/Users/lgw4/.atom/packages/language-ansible/snippets/language-ansible.cson: unexpected end of input`

**Comment by fksimon** [comment]
I just upgraded from the older version and am seeing the same problem.  Every time I start atom fresh the error occurs.   I am running on Mac with latest version of Atom.   I tried to uninstall and reinstall but the problem still occurs after first restart.

**Comment by mariusvw** [comment]
Possible solution is commenting the line:

```
.source.ansible':
```

In `~/.atom/packages/language-ansible/snippets/language-ansible.cson`

I believe this occurs only when having no snippets.

**Comment by fksimon** [comment]
Commenting the line out does fix the issue.

**Comment by haad** [comment]
This is fixen in 0.1.6 please update
